name: SimpleAdminArea
main: fr.fewerelk.simpleadminarea.SAA
author: fewerelk
version: 1.0
dependecies: #none
api-version: 1.19
commands:
  saa:
    description: All commands of SAA.
    usage: /saa <sub-command> <args>
    permission: saa.saa